# Copyright (C) 2022, Gauthier Leonard
# See the file LICENSE for licensing terms.
---
avax_transfer_to_address_bech32: C-local18jma8ppw3nhx5r4ap8clazz0dps7rv5u00z96u
avax_transfer_to_address_hex: "0x8db97C7cEcE249c2b98bDC0226Cc4C2A57BF52FC"
avax_transfer_amount_navax: 1000000000
# It is a best practice to encrypt sensitive variable using Ansible vault
# Vault password = ewoq
avax_transfer_from_username: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  65643665373461343366366161623038383134396339303931386131653662356663366530613539
  3461323730646262626531396461353164653939333730380a393637626637366136366439383035
  37653661343365376531316264316464343763356136306430383865363863343933323333373437
  6366336430313233340a343465316663653630626566363131636438333338383236613631633563
  6138
avax_transfer_from_password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  36363962333839616366363730306264373332373336316332356162323230313039393265626639
  6265613633623538396266323232353130643466646261370a653161333066663034346536346365
  38346235653736636438663265353130303665323939343663663961386635626539616464373636
  3232643435333437660a666137323964386338316361333931356232616163663636646262386130
  3461
avax_transfer_to_username: "{{ avax_transfer_from_username }}"
avax_transfer_to_password: "{{ avax_transfer_from_password }}"
